"""create_tables

Revision ID: 0c612caa7ddd
Revises: 
Create Date: 2019-07-21 22:13:37.190636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c612caa7ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('standing_charge', sa.Float(precision=2), nullable=False),
        sa.Column('call_minute_charge', sa.Float(precision=2), nullable=False),
        sa.Column('start_reduce_time', sa.Time(), nullable=True),
        sa.Column('end_reduce_time', sa.Time(), nullable=True),
        sa.Column('reduced_standing_charge', sa.Float(precision=2), nullable=False),
        sa.Column('reduced_call_minute_charge', sa.Float(precision=2), nullable=False),
        sa.Column('starts_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('call_id', sa.Integer(), nullable=False),
        sa.Column('start_timestamp', sa.DateTime(), nullable=True),
        sa.Column('origin_phone', sa.String(length=11), nullable=True),
        sa.Column('destination_phone', sa.String(length=11), nullable=True),
        sa.Column('end_timestamp', sa.DateTime(), nullable=True),
        sa.Column('fare_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['fare_id'], ['fare.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('call_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call')
    op.drop_table('fare')
    # ### end Alembic commands ###
