"""create_tables

Revision ID: 70943f626c6a
Revises: 
Create Date: 2019-07-16 19:44:58.688124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70943f626c6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('origin_phone', sa.String(length=11), nullable=False),
    sa.Column('destination_phone', sa.String(length=11), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('fare',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('standing_charge', sa.Float(precision=2), nullable=False),
    sa.Column('call_minute_charge', sa.Float(precision=2), nullable=False),
    sa.Column('start_reduce_time', sa.Time(), nullable=True),
    sa.Column('end_reduce_time', sa.Time(), nullable=True),
    sa.Column('reduced_standing_charge', sa.Float(precision=2), nullable=False),
    sa.Column('reduced_call_minute_charge', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fare')
    op.drop_table('call')
    # ### end Alembic commands ###
